# This is a basic workflow to help you get started with Actions

name: Repos mirror sync gitee

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Repo Mirror Sync Gitee
        uses: kubeservice-stack/repos-mirror-action@v1.0.3
        with:
          target-url: https://gitee.com/dongjiang1989/kspack-go.git
          target-username: dongjiang1989
          target-token: ${{ secrets.GITEE_ACTOR_SECRET }}
